# Generated by Django 5.0 on 2023-12-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',), 'verbose_name': "Murojaatlar ro'yxati", 'verbose_name_plural': 'Murojaatlar'},
        ),
    ]
