# Generated by Django 5.0.1 on 2024-01-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourapp', '0003_team_message_is_active_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_active',
        ),
    ]
